# Generated by Django 6.0.6 on 2026-07-06 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0009_projectdevice_service_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', '查看'), ('create', '新增'), ('edit', '编辑'), ('delete', '删除')], default='view', max_length=64),
        ),
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scope_type', models.CharField(choices=[('all', '全部数据'), ('self', '本人销售数据'), ('custom', '自定义销售范围')], default='custom', max_length=16)),
                ('remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSalesScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_scopes', to='accounts.useraccessprofile')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sales_scopes', to='projects.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'sales_person'), name='uniq_profile_sales_scope')],
            },
        ),
    ]
