# Generated by Django 6.0.6 on 2026-07-30 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_permission_action_useraccessprofile_and_more'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active_at', models.DateTimeField()),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='authtoken.token')),
            ],
        ),
    ]
