# Generated by Django 6.0.6 on 2026-07-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_productline_product_product_line_productversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_under_warranty',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='screenshot_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
