# Generated by Django 6.0.6 on 2026-07-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_device_is_under_warranty_device_screenshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rack_install_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
