# Generated by Django 6.0.6 on 2026-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_device_rack_install_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_standard_product',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='management_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='supports_remote',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='version_update_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdevice',
            name='device_project_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
