# Generated by Django 6.0.6 on 2026-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_device_is_standard_product_device_management_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='winning_company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
