# Generated by Django 6.0.6 on 2026-07-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_contact_company_project_winning_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_projects', to='projects.person'),
        ),
    ]
