# Generated by Django 6.0.6 on 2026-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdevice',
            name='service_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdevice',
            name='service_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdevice',
            name='service_type',
            field=models.CharField(choices=[('new_install', '新上设备'), ('renewal', '续保旧设备')], db_index=True, default='new_install', max_length=32),
        ),
    ]
