# Generated by Django 6.0.6 on 2026-07-28 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectdevice_offline_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='projects_pr_custome_271885_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='signing_subject',
            field=models.CharField(choices=[('direct', '直签'), ('agent', '代理')], db_index=True, default='direct', max_length=16),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['customer_org', 'sales_person', 'project_stage', 'signing_subject', 'status'], name='projects_pr_custome_69a1b0_idx'),
        ),
    ]
