# Generated by Django 6.0.6 on 2026-07-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_projects_pr_custome_271885_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStandardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('inspection_frequency', models.CharField(choices=[('monthly', '每月'), ('quarterly', '每季度'), ('semiannual', '每半年'), ('annual', '每年'), ('custom', '自定义天数')], default='quarterly', max_length=20)),
                ('inspection_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reminder_days', models.PositiveIntegerField(default=7)),
                ('auto_generate_tasks', models.BooleanField(default=True)),
                ('service_contents', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('inspection_frequency', models.CharField(choices=[('monthly', '每月'), ('quarterly', '每季度'), ('semiannual', '每半年'), ('annual', '每年'), ('custom', '自定义天数')], default='quarterly', max_length=20)),
                ('inspection_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('first_inspection_date', models.DateField(blank=True, null=True)),
                ('reminder_days', models.PositiveIntegerField(default=7)),
                ('auto_generate_tasks', models.BooleanField(default=True)),
                ('service_contents', models.JSONField(blank=True, default=list)),
                ('standard_snapshot', models.JSONField(blank=True, default=dict)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ops_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_service_plans', to='projects.person')),
                ('project_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to='projects.projectdevice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_service_plans', to='projects.servicestandardtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='servicestandardtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('code',), name='uniq_active_service_standard_code'),
        ),
        migrations.AddIndex(
            model_name='deviceserviceplan',
            index=models.Index(fields=['project_device', 'status'], name='projects_de_project_dc686d_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceserviceplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project_device',), name='uniq_active_project_device_service_plan'),
        ),
    ]
