# Generated by Django 6.0.6 on 2026-07-28 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_servicestandardtemplate_deviceserviceplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('planned_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', '待巡检'), ('completed', '已完成'), ('overdue', '已逾期'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16)),
                ('reminder_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_tasks', to='projects.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_tasks', to='projects.deviceserviceplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceOperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('record_type', models.CharField(choices=[('inspection', '巡检'), ('system_upgrade', '系统升级'), ('rule_library_upgrade', '规则库升级'), ('fault_handling', '故障处理'), ('configuration_change', '配置变更'), ('technical_support', '技术支持'), ('other', '其他')], db_index=True, max_length=32)),
                ('performed_at', models.DateTimeField(db_index=True)),
                ('result', models.CharField(choices=[('normal', '正常'), ('issue_found', '发现问题'), ('follow_up', '需跟进')], default='normal', max_length=20)),
                ('check_items', models.JSONField(blank=True, default=list)),
                ('issue_description', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('software_version_before', models.CharField(blank=True, default='', max_length=100)),
                ('software_version_after', models.CharField(blank=True, default='', max_length=100)),
                ('rule_library_version_before', models.CharField(blank=True, default='', max_length=100)),
                ('rule_library_version_after', models.CharField(blank=True, default='', max_length=100)),
                ('attachment_urls', models.JSONField(blank=True, default=list)),
                ('customer_confirmed_by', models.CharField(blank=True, default='', max_length=100)),
                ('customer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_records', to='projects.device')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_records', to='projects.person')),
                ('project_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_records', to='projects.projectdevice')),
                ('service_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_records', to='projects.deviceserviceplan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('inspection_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_record', to='projects.inspectiontask')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='inspectiontask',
            index=models.Index(fields=['status', 'planned_date'], name='projects_in_status_715794_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectiontask',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('service_plan', 'planned_date'), name='uniq_active_inspection_task_date'),
        ),
        migrations.AddIndex(
            model_name='deviceoperationrecord',
            index=models.Index(fields=['device', 'performed_at'], name='projects_de_device__648837_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceoperationrecord',
            index=models.Index(fields=['project_device', 'record_type', 'performed_at'], name='projects_de_project_cc88be_idx'),
        ),
    ]
