# Generated by Django 6.0.6 on 2026-07-28 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_legacy_inspection_schedules(apps, schema_editor):
    DeviceServicePlan = apps.get_model('projects', 'DeviceServicePlan')
    DeviceServiceSchedule = apps.get_model('projects', 'DeviceServiceSchedule')
    InspectionTask = apps.get_model('projects', 'InspectionTask')

    for plan in DeviceServicePlan.objects.filter(is_deleted=False):
        if 'inspection' not in (plan.service_contents or []):
            continue
        schedule, _ = DeviceServiceSchedule.objects.get_or_create(
            service_plan_id=plan.id,
            service_type='inspection',
            defaults={
                'frequency': plan.inspection_frequency,
                'interval_days': plan.inspection_interval_days,
                'first_service_date': plan.first_inspection_date,
                'reminder_days': plan.reminder_days,
                'auto_generate_tasks': plan.auto_generate_tasks,
            },
        )
        InspectionTask.objects.filter(service_plan_id=plan.id, service_schedule__isnull=True).update(
            service_schedule_id=schedule.id,
            task_type='inspection',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_inspectiontask_deviceoperationrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, default='active', max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('service_type', models.CharField(choices=[('inspection', '巡检'), ('system_upgrade', '系统升级'), ('rule_library_upgrade', '规则库升级')], db_index=True, max_length=32)),
                ('frequency', models.CharField(choices=[('monthly', '每月'), ('quarterly', '每季度'), ('semiannual', '每半年'), ('annual', '每年'), ('custom', '自定义天数')], default='quarterly', max_length=20)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('first_service_date', models.DateField(blank=True, null=True)),
                ('reminder_days', models.PositiveIntegerField(default=7)),
                ('auto_generate_tasks', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='inspectiontask',
            name='uniq_active_inspection_task_date',
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='task_type',
            field=models.CharField(choices=[('inspection', '巡检'), ('system_upgrade', '系统升级'), ('rule_library_upgrade', '规则库升级')], db_index=True, default='inspection', max_length=32),
        ),
        migrations.AddField(
            model_name='deviceserviceschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceserviceschedule',
            name='service_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='projects.deviceserviceplan'),
        ),
        migrations.AddField(
            model_name='deviceserviceschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='service_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.deviceserviceschedule'),
        ),
        migrations.RunPython(create_legacy_inspection_schedules, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inspectiontask',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('service_schedule', 'planned_date'), name='uniq_active_service_task_date'),
        ),
        migrations.AddConstraint(
            model_name='deviceserviceschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('service_plan', 'service_type'), name='uniq_active_plan_service_schedule_type'),
        ),
    ]
